### ISSUE TITLE
项目启动 访问资源服务报错

### ISSUE THREAD

**Issue by xiayimimo** [yaohw007/springcloud-oauth2#1]
![image](https://user-images.githubusercontent.com/43164237/68179466-f1664980-ffca-11e9-92dd-83bd127d14dc.png)

**Comment by copoile** [comment]
额~，
这里返回的信息是没问题的，因为你方法的接口是受保护的，没有权限访问资源。
要访问受保护的资源必须经过认证中心认证，获取到accessToken，在访问资源接口的时候在请求头带上accessToken才可以访问。

**Comment by xiayimimo** [comment]
> 这里返回的信息是没问题的，因为你方法的接口是受保护的，没有权限访问资源。
我以为能自动跳到认证服务的，需求也是这样

**Comment by copoile** [comment]
> > 这里返回的信息是没问题的，因为你方法的接口是受保护的，没有权限访问资源。
> > 我以为能自动跳到认证服务的，需求也是这样
你们项目是前后台分离的吗？如果是的话可以让前端的写一个登录的页面，然后然后如果访问的接口返回401就跳转登录页
