### ISSUE TITLE
密码模式图下半截没截全

### ISSUE THREAD

**Issue by andrew7baker** [yaohw007/springcloud-oauth2#3]
密码模式图下半截没截全，返回的应该是这个嘛?
{
    "timestamp": "2020-01-31T09:11:55.568+0000",
    "status": 401,
    "error": "Unauthorized",
    "message": "Unauthorized",
    "path": "/oauth/token"
}

**Comment by andrew7baker** [comment]
这幅图

https://github.com/yaohw007/springcloud-oauth2/blob/master/images/%E5%AF%86%E7%A0%81%E6%A8%A1%E5%BC%8F_01.png

**Comment by yaohw007** [comment]
端口对了吗？还是Basic 请求头没加上？

**Comment by yaohw007** [comment]
> 这幅图
> 
> https://github.com/yaohw007/springcloud-oauth2/blob/master/images/%E5%AF%86%E7%A0%81%E6%A8%A1%E5%BC%8F_01.png

**Comment by copoile** [comment]
> 这幅图
> 
> https://github.com/yaohw007/springcloud-oauth2/blob/master/images/%E5%AF%86%E7%A0%81%E6%A8%A1%E5%BC%8F_01.png

**Comment by copoile** [comment]
> 这幅图
> 
> https://github.com/yaohw007/springcloud-oauth2/blob/master/images/%E5%AF%86%E7%A0%81%E6%A8%A1%E5%BC%8F_01.png



> 密码模式图下半截没截全，返回的应该是这个嘛?
> {
> "timestamp": "2020-01-31T09:11:55.568+0000",
> "status": 401,
> "error": "Unauthorized",
> "message": "Unauthorized",
> "path": "/oauth/token"
> }

端口对了吗？还是Basic 请求头没加上？

**Comment by andrew7baker** [comment]
加个QQ 1738022477 我把我这边的操作情况发给你

**Comment by andrew7baker** [comment]
或者你把Authorization 里面的也截个图。

**Comment by andrew7baker** [comment]
我没注意你文字中描述的 Authorization的参数及值了。

**Comment by copoile** [comment]
现在可以了吗？我刚加你qq了，我电脑关了，邮箱回复你的。------------------ 原始邮件 ------------------
发件人: "andrew7baker"<notifications@github.com>
发送时间: 2020年1月31日(星期五) 晚上9:36
收件人: "yaohw007/springcloud-oauth2"<springcloud-oauth2@noreply.github.com>;
抄送: "yaohw007"<726856005@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [yaohw007/springcloud-oauth2] 密码模式图下半截没截全 (#3)



我没注意你文字中描述的 Authorization的参数及值了。
 
&mdash;
