### ISSUE TITLE
自定义授权页

### ISSUE THREAD

**Issue by hb0730** [yaohw007/springcloud-oauth2#7]

**Comment by copoile** [comment]
授权页面不是有吗？是自定义的啊

**Comment by hb0730** [comment]
Oauth2有一个授权页的，并非Login登录页，在[auth-server](https://github.com/copoile/springcloud-oauth2/tree/master/auth-server) 并没有找到对应的自定义授权页面

**Comment by copoile** [comment]
resource/template下面

**Comment by hb0730** [comment]
spring security oauth2 页面代码在 [WhitelabelApprovalEndpoint](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/endpoint/WhitelabelApprovalEndpoint.java) ,在 [auth-server](https://github.com/copoile/springcloud-oauth2/tree/master/auth-server/src/main/resources/templates/ftl) `resources/template`下只有[login.ftl](https://github.com/copoile/springcloud-oauth2/blob/master/auth-server/src/main/resources/templates/ftl/login.ftl)

**Comment by copoile** [comment]
这个就是授权页面，授权码模式或简化模式授权的时候就是跳转到这个页面的

**Comment by hb0730** [comment]
spring security oauth2中客户端client有一个字段叫做`isAutoApprove` [ClientDetails](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/ClientDetails.java) ,是会手动授权的

**Comment by hb0730** [comment]
![image](https://user-images.githubusercontent.com/33956166/98773381-c73c3880-2423-11eb-8faf-e9e0e5d2b001.png)

**Comment by copoile** [comment]
你这个是怎么操作的呢

**Comment by hb0730** [comment]
修改一下client auto scope就知道、可以查看clientDetails的子类

**Comment by hb0730** [comment]
[selectById](https://github.com/copoile/springcloud-oauth2/blob/master/auth-server/src/main/java/cn/poile/ucs/auth/service/SysClientDetailService.java) 其中的` autoApproveScopes.add("sever")`

可以查看父类[BaseClientDetails ](https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/provider/client/BaseClientDetails.java) 中的` boolean isAutoApprove(String scope) `

**Comment by copoile** [comment]
好的，最近太忙了，没时间去看，有时间会去看下
